use_wandb: False
use_sky: False
use_dynamic: False
use_pose_refine: False
use_metric: True
debug_mode: False

mode: 'vo' # 'vo' or 'vio'


device:
  tracker: 'cuda:0'
  mapper: 'cuda:0'

dataset:
  root: /home/lumen/workspace/datasets/VINGS-Mono-Dataset/small_city/
  module: datasets.hierarchical
  rgb_strip: 1

middleware:
  cov_times: 1000
  max_cov: 3e3
  max_depth: 35

output:
  save_dir: /home/lumen/workspace/noetic_ws/vings_ws/output/

# 707.0912 707.0912 601.8873 183.1104
intrinsic: # H, W, intrinsic就用原始的哈
  H: 690
  W: 1024
  fu: 487.09015156
  fv: 486.9700816
  cu: 345. # cy
  cv: 512. # cx
  resolution_scale: 1.0
  bg: 0


frontend:
  weight: /home/lumen/workspace/noetic_ws/vings_ws/src/VINGS-Mono/ckpts/droid.pth
  image_size: [344, 616]
  buffer: 80
  filter_thresh: 2.4
  c2i: None
  # visual_only: 0 # 0 means VIO and 1 means VO.
  warm_up: 8
  beta: 0.3
  frontend_nms: 1
  keyframe_thresh: 4.0
  frontend_window: 5
  frontend_thresh: 16.0 
  frontend_radius: 2
  active_window: 12
  # CovisibleGraph
  max_factors: 48
  far_threshold: 0.02
  inac_range: 3
  mask_threshold: -1.0
  skip_edge: [-4,-5,-6]
  translation_threshold: 0.5
  # Vis.
  show_plot: False

adc_args:
  accum_thresh: 0.98
training_args:
  num_keyframe: 8
  iters: 50
  lr: # Copy form 2DGS.
    _xyz_lr: 0.0001
    _rgb_lr: 0.0005
    _opacity_lr: 0.05
    _scaling_lr: 0.001
    _rotation_lr: 0.001
  loss_weights:
    rgb_loss: 1.0
    depth_loss: 1.0
    alpha_loss: 1.0  # 10.0
    normal_loss: 0.1 # 0.05
    dist_loss: 0.0

use_vis: True
vis:
  bev_w2c: [[ 9.86264675e-01,  7.99505779e-02,  1.44533373e-01, -5.73378037e+01],
       [ 2.78057407e-02,  7.82189932e-01, -6.22419273e-01, 3.97714933e+01],
       [-1.62815330e-01,  6.17889000e-01,  7.69223214e-01, 14.49326822e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]]
  bev_intrinsic_dict:
    H: 758
    W: 1372
    fu: 656.44725606860459
    fv: 656.44725606860459
    cu: 378.5 # cy
    cv: 685.5 # cx
  pose_scale: 1.0



# 2024/10/01
use_storage_manager: False
storage_manager:
  distance_threshold: 30.0
  
looper:
  lightglue_weight_dir: /home/lumen/workspace/noetic_ws/vings_ws/src/VINGS-Mono/ckpts/lightglue/
  onnx_w: 512
  H: 344
  W: 616
  # nearest_k_frame: 10
  loop_radius: 15
  is_loop_min_match_num: 45
  search_num: 30
  is_loop_mse_threshold: 0.15 # 0.18
  is_loop_med_times: 100.0
